let x=3;
console.log(x+3);
console.log(x-3);
console.log(x*3);
console.log(x/3);
console.log(x %3);
console.log(x++);
console.log(x);
console.log(x**3);
console.log(++x);
console.log(x--);
console.log(x);
console.log(--x);

console.log(2==2);
console.log(2==3);
console.log("2"==2);
console.log(2=="4");
console.log(2==="2");
console.log(2!=3);
console.log(3!=3);
console.log(3!=3);
console.log(2!=4);
console.log(2===2);
console.log(2==="2");
console.log(3>=3);
console.log(3<=3);
console.log(2>=3);
console.log(6>=3);
console.log(34<=44);
console.log(33<=3);